#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

display_usage() { 
	echo -e "\nUsage: $0 [options] [engine] [query]"
    echo -e "       Search for [query] using specified search engine."
	echo -e "\n       $0 [options] url [url]" 
    echo -e "       Parse a specific website/url."
    echo -e "Options:\n"
    echo -e "\t-h, --help\t\tPrint this help message and exit.\n"
    echo -e "\t-r [number]\t\tNumber of results you want the search to return (not all engines will respect this).\n"
    echo -e "\t-o\t\t\tShow only the main result group, and omit all other groups.\n"
} 

show_search() {
    local engine query
    engine=$1
    query="$2"

    # bash open.sh $engine "$(node search.js $engine "$query" | fzf --reverse --ansi --preview="node preview.js {} | xargs cat | ~/.iterm2/imgcat")"
    # bash open.sh $engine "$(node search.js $engine "$query" | fzf --reverse --ansi --header-lines=1 --preview="node preview.js {} | xargs /Users/alexander.tsepkov/work/personal/Prevu/Prevu/Prevu.app/Contents/MacOS/Prevu")"
    bash $DIR/open.sh $engine "$(node $DIR/search.js $engine "$query" | fzf --reverse --ansi --preview-window=right:40% --header-lines=1 --preview="node $DIR/preview.js $engine {}")"
}

# populates caches for all engines this script is aware of
initialize() {
    local engine
    engine=$1

    echo "Rebuilding cache for $engine..."
    mkdir -p .cache
    export CACHING=1
    node $DIR/search.js $engine
    unset CACHING
}

if [ "$#" -lt 2 ]; then
    display_usage
    exit 1
fi

while getopts ":hr:o" opt; do
    case $opt in
        h|help)  # help
            display_usage
            exit 0
            ;;
        r|results)  # number of results to prefer
            export RESULTS=$OPTARG; shift
            ;;
        o|only)  # number of results to prefer
            export ONLY_MAIN=1; shift
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done

if [ "$1" != "url" ]; then
    if [ ! -d $DIR/.cache ] || [ ! -f $DIR/.cache/$1-template.json ]; then
        initialize $1
    fi
fi
show_search $1 "$2"
