#!/usr/bin/env bash

display_usage() { 
	echo -e "\nUsage: $0 [options] [engine] [query] \n" 
    echo -e "Options:\n"
    echo -e "\t-h, --help\t\tPrint this help message and exit.\n"
    echo -e "\t-r [number]\t\tNumber of results you want the search to return (not all engines will respect this).\n"
} 

show_search() {
    local engine query
    engine=$1
    query="$2"

    # bash open.sh $engine "$(node search.js $engine "$query" | fzf --reverse --ansi --preview="node preview.js {} | xargs cat | ~/.iterm2/imgcat")"
    # bash open.sh $engine "$(node search.js $engine "$query" | fzf --reverse --ansi --header-lines=1 --preview="node preview.js {} | xargs /Users/alexander.tsepkov/work/personal/Prevu/Prevu/Prevu.app/Contents/MacOS/Prevu")"
    bash open.sh $engine "$(node search.js $engine "$query" | fzf --reverse --ansi --preview-window=right:40% --header-lines=1 --preview="node preview.js $engine {}")"
}

# populates caches for all engines this script is aware of
initialize() {
    echo "Rebuilding cache...\n"
    mkdir -p .cache
}

if [ "$#" -lt 2 ]; then
    display_usage
    exit 1
fi

while getopts ":hr:u" opt; do
    case $opt in
        h|help)  # help
            display_usage
            exit 0
            ;;
        r|results)  # number of results to prefer
            export RESULTS=$OPTARG; shift
            ;;
        u)  # update cache
            initialize
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done

if [ ! -d .cache ]; then
    initialize
fi
show_search $1 "$2"
